# Generated by Django 4.1.7 on 2023-06-06 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('application', '0002_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='user.seeker'),
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
        migrations.AddField(
            model_name='application',
            name='job_applications',
            field=models.ManyToManyField(related_name='application_documents', to='application.jobapplication'),
        ),
        migrations.AddField(
            model_name='applicantdoc',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.seeker'),
        ),
    ]
