# Generated by Django 4.1.7 on 2023-05-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='job_sector',
            field=models.ManyToManyField(blank=True, related_name='seeker_sector', to='user.sector'),
        ),
    ]
