# Generated by Django 4.1.7 on 2023-05-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_seeker_job_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='job_sector',
            field=models.ManyToManyField(blank=True, related_name='sector_list', to='user.sector'),
        ),
    ]
