# Generated by Django 4.1.7 on 2023-05-20 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_seeker_job_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_sector', to=settings.AUTH_USER_MODEL),
        ),
    ]
