# Generated by Django 4.1.7 on 2023-05-20 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_sector_seeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_sector', to='user.seeker'),
        ),
    ]
