# Generated by Django 4.1.7 on 2023-04-23 10:01

from django.db import migrations, models
import django.db.models.deletion
import job.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=job.models.job_logo_directory_path)),
                ('sector', models.CharField(choices=[('', 'select'), ('advertising-media-communications', 'Advertising, Media & Communications'), ('agriculture-fishing-forestry', 'Agriculture, Fishing & Forestry'), ('automotive-aviation', 'Automotive & Aviation'), ('banking-finance-insurance', 'Banking, Finance & Insurance'), ('construction', 'Construction'), ('education', 'Education'), ('energy-utilities', 'Energy & Utilities'), ('enforcement-security', 'Enforcement & Security'), ('entertainment-events-sport', 'Entertainment, Events & Sport'), ('government', 'Government'), ('healthcare', 'Healthcare'), ('hospitality-hotel', 'Hospitality & Hotel'), ('it-telecoms', 'IT & Telecoms'), ('law-compliance', 'Law & Compliance'), ('manufacturing-warehousing', 'Manufacturing & Warehousing'), ('mining-energy-metals', 'Mining, Energy & Metals'), ('ngo-npo-charity', 'NGO, NPO & Charity'), ('real-estate', 'Real Estate'), ('recruitment', 'Recruitment'), ('retail-fashion-fmcg', 'Retail, Fashion & FMCG'), ('shipping-logistics', 'Shipping & Logistics'), ('tourism-travel', 'Tourism & Travel')], default='', max_length=50)),
                ('type_of_job', models.CharField(choices=[('', 'select'), ('accounting-auditing-finance', 'Accounting, Auditing & Finance'), ('admin-office', 'Admin & Office'), ('building-architecture', 'Building & Architecture'), ('community-social-services', 'Community & Social Services'), ('consulting-strategy', 'Consulting & Strategy'), ('creative-design', 'Creative & Design'), ('customer-service-support', 'Customer Service & Support'), ('driver-transport-services', 'Driver & Transport Services'), ('engineering-technology', 'Engineering & Technology'), ('estate-agent-property-management', 'Estate Agents & Property Management'), ('farming-agriculture', 'Farming & Agriculture'), ('food-services-catering', 'Food Services & Catering'), ('health-safety', 'Health & Safety'), ('hospitality-leisure', 'Hospitality & Leisure'), ('human-resources', 'Human Resources'), ('legal-services', 'Legal Services'), ('management-business-development', 'Management & Business Development'), ('marketing-communications', 'Marketing & Communications'), ('medical-pharmaceutical', 'Medical & Pharmaceutical'), ('product-project-management', 'Product & Project Management'), ('quality-control-assurance', 'Quality Control & Assurance'), ('research-teaching-training', 'Research, Teaching & Training'), ('sales', 'Sales'), ('software-data', 'Software & Data'), ('supply-chain-procurement', 'Supply Chain & Procurement'), ('trades-services', 'Trades & Services')], default='', max_length=50)),
                ('deadline', models.DateTimeField()),
                ('minimum_qualification', models.CharField(choices=[('', 'select'), ('degree', 'Degree'), ('diploma', 'Diploma'), ('wassce-ssce', 'WASSCE / SSCE'), ('hnd', 'HND'), ('mba-msc', 'MBA / MSc'), ('mbbs', 'MBBS'), ('mphil-phd', 'MPhil / PhD'), ('nce', 'NCE'), ('ond', 'OND'), ('others', 'Others'), ('vocational', 'Vocational')], default='', max_length=20)),
                ('type_of_employment', models.CharField(choices=[('', 'select'), ('full-time', 'Full-time'), ('part-time', 'Part-time'), ('freelance', 'Freelance'), ('contract', 'Contract'), ('Internship', 'Internship'), ('apprenticeship', 'Apprenticeship'), ('seasonal', 'Seasonal')], default='', max_length=30)),
                ('experience_length', models.IntegerField(default=1)),
                ('number_of_required_applicantion', models.IntegerField(default=1)),
                ('slug', models.SlugField(blank=True)),
                ('type_of_publisher', models.CharField(choices=[('C', 'Company Representative'), ('S', 'Staff')], default='S', max_length=2)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assign', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_responsibility', to='job.job')),
            ],
            options={
                'verbose_name': 'Responsibility',
                'verbose_name_plural': 'Responsibilities',
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requires', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requirement', to='job.job')),
            ],
            options={
                'verbose_name': 'Requirement',
                'verbose_name_plural': 'Requirements',
            },
        ),
        migrations.CreateModel(
            name='JobApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_publish', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_approval_jobs', to='job.job')),
            ],
            options={
                'verbose_name': 'Job Approval',
                'verbose_name_plural': 'Jobs Approval',
            },
        ),
    ]
