# Generated by Django 4.1.7 on 2023-03-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='job_requirements', to='job.requirement'),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=models.ManyToManyField(blank=True, related_name='job_responsibilities', to='job.responsibility'),
        ),
    ]
